AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
  UseCache: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 50

Metrics/AbcSize:
  Max: 65

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 12

Layout/LineLength:
  Max: 120

Gemspec/DevelopmentDependencies:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false
